name: Goal microservice Build/Test

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Set GoalApiKey
      run: |
        if [ ${{ secrets.GOAL_API_KEY != "" }} ]; then 
          dotnet user-secrets set "GoalApiKey" "${{ secrets.GOAL_API_KEY }}" --project Goal/src/jiraF.Goal.API/
        else
          dotnet user-secrets set "GoalApiKey" "12345testApiKey" --project Goal/src/jiraF.Goal.API/
        fi
    - name: Restore dependencies
      run: dotnet restore Goal
    - name: Build
      run: dotnet build Goal --no-restore
    - name: Test
      run: dotnet test Goal --no-build --verbosity normal
